SPECIES_NAME = config["common_species_name"]
WSSD_THRESHOLD_5KB = config["wssd_threshold_5kb"]
WSSD_THRESHOLD_1KB = WSSD_THRESHOLD_5KB / 5

with open(config["clone_ids"], "r") as clone_ids_fh:
    ACCESSIONS = [line.rstrip() for line in clone_ids_fh]

TOTAL_ACCESSIONS = len(ACCESSIONS)

rule parasight_graph:
    input: "wins/5-1_norpt_iden.tab"
    output: "graph1.tab"
    params: sge_opts=""
    shell: "graph_maker.pl {input} {output} 5000 5 0"

rule parasight_sequences:
    input: "bac.out"
    output: "showseq.out"
    params: sge_opts=""
    shell: """echo -e "seqname\\tlength" > {output}; sort {input} >> {output}"""

rule parasight_alignment:
    input: "wins/5-1_norpt_iden.tab", "bac.out"
    output: "species.align"
    params: sge_opts=""
    shell: "perl ~ginger2/bin/align_maker.pl {input} {output}"

rule wssd_for_all_accessions:
    input: config["clone_ids"], "wssd_bases_by_accession.tab"
    output: "wssd_for_all_accessions.tab"
    params: sge_opts=""
    shell: """join -j 1 -a 1 -e 0 -o 1.1 2.2 -t"	" {input} | cut -f 2 | awk 'OFS="\\t" {{ if (NR == 1) {{ print "wssd" }} print }}' > {output}"""

rule wssd_bases_by_accession:
    input: "wins/wssdGE10K_nogap.tab"
    output: "wssd_bases_by_accession.tab"
    params: sge_opts=""
    shell: """sed '/_rc/d' {input} | awk 'OFS="\\t" {{ print $1,$3-$2 }}' | groupBy -i stdin -g 1 -c 2 -o sum > {output}"""

rule remove_gaps_from_wssd:
    input: wssd="wins/wssdGE10K.tab", gaps="gaps.tab"
    output: "wins/wssdGE10K_nogap.tab"
    params: sge_opts=""
    shell: "twoPartOvp_mgsrt.pl -i {input.wssd} -f -j {input.gaps} -t -L -o {output}"

rule filter_wssd_by_size:
    input: "wins/wssd.merged"
    output: "wins/wssdGE10K.tab"
    params: sge_opts=""
    shell: "awk '$3 - $2 >= 10000' {input} > {output}"

rule merge_wssd_windows:
    input: "wins/wssd.tab"
    output: "wins/wssd.merged"
    params: sge_opts=""
    shell: "coordsMerger_sort.pl -i {input} -h -u -n 0 -b 1 -e 2 -o {output}"

rule pick_wssd_windows:
    input: threshold_5kb="wins/5-1_norpt_iden.tab", threshold_1kb="wins/1-1_norpt_iden.tab"
    output: "wins/wssd.tab"
    params: sge_opts=""
    shell: "wssd_picker.pl -f {input.threshold_5kb} -w 7 -s 6 -c {WSSD_THRESHOLD_5KB} -b 3 -k {input.threshold_1kb} -n 5 -i 1 -t {WSSD_THRESHOLD_1KB} -o {output}"

rule calculate_depth_in_nonsliding_windows:
    input: windows="wins/wssd_depth_windows.bed", reads="wins/rd.out"
    output: "wins/wssd_depth_in_windows.bedGraph"
    params: sge_opts=""
    shell: "bedtools intersect -a {input.windows} -b {input.reads} -c > {output}"

rule create_nonsliding_windows:
    input: "bac.out"
    output: "wins/wssd_depth_windows.bed"
    params: sge_opts=""
    shell: "bedtools makewindows -g {input} -w 1000 > {output}"

rule calculate_depth_stats:
    input: "wins/5-1_norpt_iden.tab"
    output: "wins/depth_stats.txt"
    params: sge_opts=""
    shell: """cut -f 4 {input} | grep -P "^\d+$" | statStd.pl > {output}"""

rule calculate_depth_in_1kb_windows:
    input: depth="wins/rd.out", sizes="bac.out", nonrepeats="norptgap.tab"
    output: "wins/1-1_norpt_iden.tab"
    params: sge_opts=""
    shell: "windowTracks_ovp.pl -w 1 -s 1 -a {input.sizes} -i {input.nonrepeats} -f -k {input.depth} -t -e -y 3 -g 4 -o {output} > /dev/null"

rule calculate_depth_in_5kb_windows:
    input: depth="wins/rd.out", sizes="bac.out", nonrepeats="norptgap.tab"
    output: "wins/5-1_norpt_iden.tab"
    params: sge_opts=""
    shell: "windowTracks_ovp.pl -w 5 -s 1 -a {input.sizes} -i {input.nonrepeats} -f -k {input.depth} -t -e -y 3 -g 4 -o {output} > /dev/null"

rule calculate_read_depth:
    input: "post_mega", "norptgap.tab"
    output: "wins/rd.out"
    params: sge_opts=""
    run:
        if config.get("wssd_database_type") == "protein":
            shell("mkdir -p $(dirname {output}); mega_wincln_qual_parser.pl -b %s -d {input[0]} -s .bo.bo -c -i 94 -e -a 300 -r {input[1]} -m 200 -h 200 -p 0.4 -o {output} -q -t > /dev/null;" % config.get("wssd_database"))
        else:
            shell("mkdir -p $(dirname {output}); mega_wincln_qual_parser.pl -d {input[0]} -s .bo.bo -c -i 94 -e -a 300 -r {input[1]} -m 200 -h 200 -p 0.4 -o {output} -q -t > /dev/null;")

rule post_blast:
    input: "mega64_out"
    output: "post_mega"
    params: cores=str(TOTAL_ACCESSIONS + 1), sge_opts=""
    shell: "mkdir -p {output}; qsub -N post_wssd_{SPECIES_NAME} -sync y -cwd -q all.q -l h_vmem=4G -pe orte 2-{params.cores} ~jlhudd/wssd/mega64.sh -p -s {SPECIES_NAME} -b /var/tmp/{SPECIES_NAME}_wssd -i `pwd`/{input} -o `pwd`/{output}"

rule blast:
    input: "all_masked"
    output: "mega64_out"
    params: cores=str(TOTAL_ACCESSIONS + 1), sge_opts=""
    shell: "mkdir -p {output}; qsub -N wssd_{SPECIES_NAME} -sync y -cwd -q all.q -l h_vmem=4G -pe orte 2-{params.cores} ~jlhudd/wssd/mega64.sh -s {SPECIES_NAME} -b /var/tmp/{SPECIES_NAME}_wssd -i {input} -o `pwd`/{output}"
